import json
from app.database import Database
from sqlalchemy import text

RESTAURANTS = [
    {
        "restaurant_name": "Spice Garden",
        "destination": "Kandy",
        "country": "Sri Lanka",
        "cuisine": "Sri Lankan",
        "description": "An authentic Sri Lankan dining experience in the heart of Kandy. Known for our traditional rice and curry spreads, fragrant curries, and hoppers made fresh to order. The garden seating overlooking the lake makes every meal memorable.",
        "price_range": "$$",
        "rating": 4.5,
        "address": "12 Lake Drive, Kandy",
        "phone": "+94-81-2234567",
        "website": "https://spicegardenvkandy.lk",
        "opening_hours": "11:00 AM – 10:00 PM",
        "popular_dishes": json.dumps(["Kottu Roti", "Fish Ambul Thiyal", "String Hoppers", "Pol Sambol", "Wambatu Moju"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": True,
        "wifi": True,
        "parking": True,
        "live_music": False,
        "is_featured": True,
        "latitude": 7.2906,
        "longitude": 80.6337,
        "image": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Kerala Kitchen",
        "destination": "Kochi",
        "country": "India",
        "cuisine": "Indian",
        "description": "Coastal Kerala flavours served in a charming colonial-era building. Our chefs use fresh catches from the Arabian Sea and spices from local farms. Don't miss the fish molee and appam combo — a true Kerala classic.",
        "price_range": "$$",
        "rating": 4.7,
        "address": "Fort Kochi, Matthew Street, Kochi",
        "phone": "+91-484-2219876",
        "website": "https://keralakitchencochin.in",
        "opening_hours": "12:00 PM – 11:00 PM",
        "popular_dishes": json.dumps(["Fish Molee", "Appam & Stew", "Malabar Biryani", "Prawn Curry", "Kerala Parotta"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": True,
        "accepts_reservations": True,
        "wifi": True,
        "parking": True,
        "live_music": True,
        "is_featured": True,
        "latitude": 9.9312,
        "longitude": 76.2673,
        "image": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Thai Orchid",
        "destination": "Bangkok",
        "country": "Thailand",
        "cuisine": "Thai",
        "description": "Award-winning Thai restaurant nestled along the Chao Phraya River. Signature dishes blend traditional recipes with modern presentation. The sunset views from the riverside terrace are unmatched.",
        "price_range": "$$$",
        "rating": 4.8,
        "address": "45 Riverside Plaza, Charoen Krung Rd, Bangkok",
        "phone": "+66-2-639-1234",
        "website": "https://thaiorchidbkk.com",
        "opening_hours": "11:30 AM – 11:30 PM",
        "popular_dishes": json.dumps(["Tom Yum Goong", "Pad Thai", "Green Curry", "Mango Sticky Rice", "Som Tum"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": True,
        "wifi": True,
        "parking": True,
        "live_music": False,
        "is_featured": True,
        "latitude": 13.7234,
        "longitude": 100.5167,
        "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Sakura Ramen House",
        "destination": "Tokyo",
        "country": "Japan",
        "cuisine": "Japanese",
        "description": "A cozy ramen shop in Shibuya serving rich tonkotsu broth simmered for 18 hours. The handmade noodles and melt-in-your-mouth chashu pork draw queues every evening. Simple decor, extraordinary flavour.",
        "price_range": "$",
        "rating": 4.6,
        "address": "2-18-11 Shibuya, Tokyo",
        "phone": "+81-3-5485-6789",
        "website": None,
        "opening_hours": "11:00 AM – 2:00 AM",
        "popular_dishes": json.dumps(["Tonkotsu Ramen", "Miso Ramen", "Gyoza", "Karaage", "Edamame"]),
        "vegetarian_options": False,
        "outdoor_seating": False,
        "delivery_available": True,
        "accepts_reservations": False,
        "wifi": True,
        "parking": False,
        "live_music": False,
        "is_featured": False,
        "latitude": 35.6580,
        "longitude": 139.7016,
        "image": "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1552611052-33e04de1b100?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Colombo Street Bites",
        "destination": "Colombo",
        "country": "Sri Lanka",
        "cuisine": "Street Food",
        "description": "Vibrant street-food hall bringing Colombo's best flavours under one roof. From isso wade to kottu, every stall is run by a local legend. Lively atmosphere with shared tables and cold King Coconut.",
        "price_range": "$",
        "rating": 4.3,
        "address": "Galle Road, Colombo 3",
        "phone": "+94-11-2345678",
        "website": None,
        "opening_hours": "5:00 PM – 12:00 AM",
        "popular_dishes": json.dumps(["Isso Wade", "Kottu Roti", "Rolls", "Wade", "King Coconut"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": False,
        "wifi": False,
        "parking": True,
        "live_music": True,
        "is_featured": False,
        "latitude": 6.9218,
        "longitude": 79.8444,
        "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "The Coconut Tree",
        "destination": "Galle",
        "country": "Sri Lanka",
        "cuisine": "Sri Lankan",
        "description": "Rustic beachside restaurant right on Unawatuna beach. Fresh seafood grilled to perfection while you sink your toes in the sand. Famous for their garlic butter prawns and coconut cocktails.",
        "price_range": "$$",
        "rating": 4.4,
        "address": "Unawatuna Beach, Galle",
        "phone": "+94-91-2243567",
        "website": None,
        "opening_hours": "10:00 AM – 10:30 PM",
        "popular_dishes": json.dumps(["Garlic Butter Prawns", "Grilled Snapper", "Coconut Roti", "Lagoon Crab Curry", "Pineapple Curry"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": True,
        "wifi": False,
        "parking": True,
        "live_music": False,
        "is_featured": True,
        "latitude": 6.0174,
        "longitude": 80.2465,
        "image": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Bali Bamboo",
        "destination": "Bali",
        "country": "Indonesia",
        "cuisine": "Indonesian",
        "description": "A sustainable bamboo restaurant in Ubud surrounded by rice terraces. Plant-based and locally sourced menu with Balinese and pan-Asian influences. The open-air bamboo architecture is stunning.",
        "price_range": "$$$",
        "rating": 4.9,
        "address": "Jl. Raya Tegallalang, Ubud, Bali",
        "phone": "+62-361-987654",
        "website": "https://balibamboorestaurant.com",
        "opening_hours": "8:00 AM – 10:00 PM",
        "popular_dishes": json.dumps(["Nasi Goreng", "Gado-Gado", "Babi Guling", "Satay Lilit", "Dadar Gulung"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": True,
        "accepts_reservations": True,
        "wifi": True,
        "parking": True,
        "live_music": False,
        "is_featured": True,
        "latitude": -8.4313,
        "longitude": 115.2793,
        "image": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Havana Smokehouse",
        "destination": "Havana",
        "country": "Cuba",
        "cuisine": "Cuban",
        "description": "Lively Cuban restaurant in Old Havana with live salsa music every weekend. Slow-smoked meats, classic ropa vieja, and mojitos made with fresh sugarcane. The rooftop terrace offers panoramic city views.",
        "price_range": "$$",
        "rating": 4.5,
        "address": "Calle Obispo 214, Old Havana",
        "phone": "+53-7-867-4321",
        "website": "https://havanasmokehouse.cu",
        "opening_hours": "12:00 PM – 12:00 AM",
        "popular_dishes": json.dumps(["Ropa Vieja", "Lechon Asado", "Tostones", "Moros y Cristianos", "Flan Cubano"]),
        "vegetarian_options": False,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": True,
        "wifi": False,
        "parking": False,
        "live_music": True,
        "is_featured": False,
        "latitude": 23.1395,
        "longitude": -82.3539,
        "image": "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Paheli Fine Dining",
        "destination": "Jaipur",
        "country": "India",
        "cuisine": "Indian",
        "description": "Royal Rajasthani dining experience inside a restored heritage haveli. Our chefs recreate palace recipes passed down through generations. The thali is a feast for all senses — rich, colourful, and abundant.",
        "price_range": "$$$",
        "rating": 4.7,
        "address": "Nahargarh Road, Jaipur",
        "phone": "+91-141-2345678",
        "website": "https://pahelifinedining.in",
        "opening_hours": "7:00 PM – 11:30 PM",
        "popular_dishes": json.dumps(["Laal Maas", "Dal Bati Churma", "Gatte ki Sabzi", "Ker Sangri", "Mawa Kachori"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": True,
        "wifi": True,
        "parking": True,
        "live_music": True,
        "is_featured": True,
        "latitude": 26.9124,
        "longitude": 75.7873,
        "image": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Bay of Bengal Seafood",
        "destination": "Chennai",
        "country": "India",
        "cuisine": "Seafood",
        "description": "Perched on Elliot's Beach with the waves crashing below, this seafood restaurant serves the freshest catch of the day. Our Meen Kuzhambu and Prawn Biryani are local legends.",
        "price_range": "$$",
        "rating": 4.3,
        "address": "Elliot's Beach Road, Besant Nagar, Chennai",
        "phone": "+91-44-23456789",
        "website": None,
        "opening_hours": "11:00 AM – 10:30 PM",
        "popular_dishes": json.dumps(["Meen Kuzhambu", "Prawn Biryani", "Squid Fry", "Fish Tikka", "Butter Garlic Prawns"]),
        "vegetarian_options": False,
        "outdoor_seating": True,
        "delivery_available": True,
        "accepts_reservations": False,
        "wifi": False,
        "parking": True,
        "live_music": False,
        "is_featured": False,
        "latitude": 12.9988,
        "longitude": 80.2676,
        "image": "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Hanoi Train Street Café",
        "destination": "Hanoi",
        "country": "Vietnam",
        "cuisine": "Vietnamese",
        "description": "Tiny café squeezed between the famous Train Street tracks in Hanoi's Old Quarter. Sip egg coffee and nibble on banh mi while trains pass inches away. An unforgettable Hanoi experience.",
        "price_range": "$",
        "rating": 4.4,
        "address": "Train Street, Hang Bong, Hanoi",
        "phone": "+84-24-3823-4567",
        "website": None,
        "opening_hours": "7:00 AM – 9:00 PM",
        "popular_dishes": json.dumps(["Egg Coffee", "Banh Mi", "Pho Bo", "Bun Cha", "Che Ba Mau"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": False,
        "wifi": True,
        "parking": False,
        "live_music": False,
        "is_featured": False,
        "latitude": 21.0285,
        "longitude": 105.8523,
        "image": "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=85"
        ]),
    },
    {
        "restaurant_name": "Sigiriya Rock Café",
        "destination": "Sigiriya",
        "country": "Sri Lanka",
        "cuisine": "Sri Lankan",
        "description": "Dine with a view of the legendary Sigiriya Rock Fortress. Our open-air café serves traditional Sri Lankan rice plates and fresh tropical juices. Perfect stop before or after climbing the rock.",
        "price_range": "$",
        "rating": 4.2,
        "address": "Kassapa Road, Sigiriya",
        "phone": "+94-66-2234567",
        "website": None,
        "opening_hours": "8:00 AM – 6:00 PM",
        "popular_dishes": json.dumps(["Rice & Curry Plate", "Pol Roti", "Lunu Miris", "Wood Apple Juice", "Kiribath"]),
        "vegetarian_options": True,
        "outdoor_seating": True,
        "delivery_available": False,
        "accepts_reservations": False,
        "wifi": False,
        "parking": True,
        "live_music": False,
        "is_featured": False,
        "latitude": 8.0248,
        "longitude": 80.7629,
        "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=85",
        "images": json.dumps([
            "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=85",
            "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=85"
        ]),
    },
]


def seed():
    engine = Database.engine()
    with engine.begin() as conn:
        result = conn.execute(text("SELECT COUNT(*) FROM restaurants"))
        count = result.scalar()
        if count > 0:
            print(f"  Restaurants table already has {count} rows. Clearing and re-seeding...")
            conn.execute(text("DELETE FROM restaurants"))

        for r in RESTAURANTS:
            conn.execute(text("""
                INSERT INTO restaurants
                    (restaurant_name, destination, country, cuisine, description,
                     price_range, rating, address, phone, website, opening_hours,
                     popular_dishes, vegetarian_options, outdoor_seating, delivery_available,
                     accepts_reservations, wifi, parking, live_music, is_featured,
                     latitude, longitude, image, images)
                VALUES
                    (:restaurant_name, :destination, :country, :cuisine, :description,
                     :price_range, :rating, :address, :phone, :website, :opening_hours,
                     :popular_dishes, :vegetarian_options, :outdoor_seating, :delivery_available,
                     :accepts_reservations, :wifi, :parking, :live_music, :is_featured,
                     :latitude, :longitude, :image, :images)
            """), r)
            print(f"  [OK] {r['restaurant_name']} ({r['destination']}, {r['cuisine']})")

    print(f"\nDone! Seeded {len(RESTAURANTS)} restaurants.")


if __name__ == "__main__":
    print("Seeding restaurants...\n")
    seed()
